### ISSUE TITLE
Launching project in runtime without clicking on a runtime app before crashes the app

### ISSUE THREAD

**Issue by MK6554** [Pedrokostam/OkapiLauncher#80]
![image](https://github.com/user-attachments/assets/539e7950-03b7-405e-80db-5e190d7990c5)

**Comment by Pedrokostam** [comment]
Problem was caused by not setting the project path correctly in the launch options. Before the quick launch button the user would have to select the app anyway, which would set the path. 

But with the button, the app does not really get selected and the path remained null (or to be more precise, its value was the last set value - if you loaded project A, clicked on a runtime app, loaded project B and use the quick launch button, the runtime app would load project A).

Now it is set properly ( ea9dfd7fffb48c1dcbc88db54e7ee42c3a37e586)
